version: '3.8'

services:
  app:
    build: .
    container_name: products-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_URI_FILE: /run/secrets/mongo_uri
    depends_on: []
